manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: caksoylar
      url-base: https://github.com/caksoylar

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: a23aa009d7a07d67fe5609caca7372e16610f238
      import: app/west.yml

    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: a1a0f35ab6750c8fc72b84ea00add1e5fbaea1e4

    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: b0b8cc2bc79f9bf3c76cf31dbd8ee1eee575a3b1

  self:
    path: config
